export const users = [
  {
    username: "bigbear790",
    email: "scott.c@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    username: "bigmeercat392",
    email: "arianna.v@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    username: "bluemeercat818",
    email: "soumia.v@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Paused",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    username: "whitemouse602",
    email: "elli.y@kpi.com",
    memberSince: "Dec 17, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    username: "lazytiger337",
    email: "lucia.g@kpi.com",
    memberSince: "Dec 14, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    username: "bigbear790",
    email: "scott.c@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    username: "bigmeercat392",
    email: "arianna.v@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    username: "bluemeercat818",
    email: "soumia.v@kpi.com",
    memberSince: "Dec 20, 2016",
    memberships: 1,
    status: "Paused",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    username: "whitemouse602",
    email: "elli.y@kpi.com",
    memberSince: "Dec 17, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    username: "lazytiger337",
    email: "lucia.g@kpi.com",
    memberSince: "Dec 14, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
export const sections = [
  {
    title: "Computer Science and Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
  {
    title: "Electrical and Electronics Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
  {
    title: "Mechanical Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
];
