export const users = [
  {
    username: "bigbear790",
    name: "Scott Carroll",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    username: "bigmeercat392",
    name: "Arianna Van hedel",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    username: "bluemeercat818",
    name: "Soumia Velthuis",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Paused",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    username: "whitemouse602",
    name: "Elli Ylitalo",
    memberSince: "December 17, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    username: "lazytiger337",
    name: "Lucia Gallego",
    memberSince: "December 14, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    username: "bigbear790",
    name: "Scott Carroll",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    username: "bigmeercat392",
    name: "Arianna Van hedel",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    username: "bluemeercat818",
    name: "Soumia Velthuis",
    memberSince: "December 20, 2016",
    memberships: 1,
    status: "Paused",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    username: "whitemouse602",
    name: "Elli Ylitalo",
    memberSince: "December 17, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    username: "lazytiger337",
    name: "Lucia Gallego",
    memberSince: "December 14, 2016",
    memberships: 1,
    status: "Active",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
];
export const sections = [
  {
    title: "Computer Science and Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
  {
    title: "Electrical and Electronics Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
  {
    title: "Mechanical Engineering",
    subtitle: "Khulna Polytechnic Institute",
  },
];
